services:
    _defaults:
        autowire: true
        autoconfigure: true

    TillKubelke\ModuleMarketplace\:
        resource: '../../src/'
        exclude:
            - '../../src/Entity/'
            - '../../src/MarketplaceModuleBundle.php'

    TillKubelke\ModuleMarketplace\Controller\:
        resource: '../../src/Controller/'
        tags: ['controller.service_arguments']



